language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_install:
    # Update system
    - sudo apt-get update -qq
    - composer self-update

install:
    # Dependencies
    - sudo apt-get install -qq -y --force-yes php5-curl php5-mysql php5-intl php5-sqlite sqlite3

    # PHP configuration
    - phpenv config-add app/travis-ci/php-config.ini
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

    # App configuration
    - cp app/travis-ci/parameters.yml app/config/parameters.yml

    # App install
    - SYMFONY_ENV=test composer install --prefer-dist --no-progress --no-interaction

before_script:
    # Init backend data
    - ./reset.sh --env=test

script:
    - composer test

after_failure:
    # Dump log
    - cat app/logs/prod.log
    - cat app/logs/dev.log
    - cat /var/log/php-errors.log

after_scripts:
    - echo "TRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT"
