imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

# Framework Configuration
framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session: false
    fragments: false
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# REST Configuration
fos_rest:
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    allowed_methods_listener: true
    param_fetcher_listener: true
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: force
        serialize_null: true
        formats:
            xml: false
            json: true
        templating_formats:
            html: false
    format_listener:
        rules:
            -
                path: /api
                priorities: ['application/json', '*/*']
                fallback_format: json
                prefer_extension: true
            -
                path: '^/'
                priorities: [ 'text/html', '*/*']
                fallback_format: html
                prefer_extension: true

# Framework Extra Configuration
sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

# Serializer Configuration
jms_serializer:
    metadata:
        auto_detection: true

# Nelmio API documentation
nelmio_api_doc:
    name: 'OpenLocalization API documentation'
    request_listener: false
    sandbox:
        request_format:
            formats:
                json: application/json
            method: accept_header

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Authorization', 'Origin', 'X-Requested-With', 'Content-Type', 'Accept']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            #expose_headers: ['*']
            max_age: 3600
