imports:
    - { resource: config_dev.yml }

parameters:
    test.client.class: Openl10n\Bundle\ApiBundle\Test\Client

framework:
    test: ~
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false
