openl10n_api:
    type: rest
    resource: "@Openl10nApiBundle/Resources/config/routing.yml"
    prefix:   /api
    options:
        expose: true

fos_js:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Last route: match all possible pattern
openl10n_index:
    pattern:  /{path}
    requirements:
        _locale: ".*"
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Openl10nWebBundle::index.html.twig
        path: ~
