fos_js:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

openl10n_api:
    type: rest
    resource: "@Openl10nApiBundle/Resources/config/routing.yml"
    prefix:   /api
    options:
        expose: true

# Last route: match all possible patterns
openl10n_index:
    pattern:  /{path}
    requirements:
        path: "^(?!(api|assets)/).*"
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Openl10nWebBundle::index.html.twig
        path: ~
