# API docs
nelmio_api_docs:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/docs

# API entry points
openl10n_api:
    resource: "@Openl10nApiBundle/Resources/config/routing.yml"
    prefix:   /api

# App (must be last route, ie. match all other patterns)
openl10n_app:
    pattern: /app
    defaults:
        _controller: FrameworkBundle:Template:template
        template: ::app.html.twig

# App (must be last route, ie. match all other patterns)
openl10n_index:
    pattern:  /{path}
    requirements:
        path: "^(?!(api|assets)/).*"
    defaults:
        _controller: FrameworkBundle:Template:template
        template: ::index.html.twig
        path: ~
