# API routes
openl10n_api:
    resource: "@Openl10nApiBundle/Resources/config/routing.yml"
    prefix:   /api

# Last route: match all possible patterns
openl10n_index:
    pattern:  /{path}
    requirements:
        path: "^(?!(api|assets)/).*"
    defaults:
        _controller: FrameworkBundle:Template:template
        template: ::index.html.twig
        path: ~
