security:
    encoders:
        Openl10n\Bundle\UserBundle\Security\User\User: sha512
        Openl10n\Domain\User\Model\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: openl10n.security.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_docs:
            pattern:    ^/api/docs
            security: false

        api:
            pattern:    ^/api
            anonymous: ~
            stateless: true
            http_basic:
                realm: "API access"

        main:
            pattern:    ^/
            security: false

    access_control:
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
