namespaces:
    Openl10nCore: Openl10n\Bundle\CoreBundle\Validator\Constraints\

Openl10n\Bundle\CoreBundle\Action\CreateProjectAction:
    properties:
        name:
            - NotBlank: ~
        slug:
            - NotBlank: ~
            - Regex: "/^[a-zA-Z0-9\-\.\_]+$/"
            - Openl10nCore:UniqueProject: ~
        defaultLocale:
            - NotBlank: ~

Openl10n\Bundle\CoreBundle\Action\EditProjectAction:
    properties:
        name:
            - NotBlank: ~
        defaultLocale:
            - NotBlank: ~

Openl10n\Bundle\CoreBundle\Action\ImportDomainAction:
    properties:
        file:
            - NotBlank: ~
        slug:
            - NotBlank: ~
        locale:
            - NotBlank: ~
