Openl10n\Bundle\CoreBundle\Model\Domain:
    exclusion_policy: ALL
    properties:
        id:
            expose: false
        slug:
            expose: true
            inline: true
        name:
            expose: true
            inline: true

