project:
    type: rest
    resource: Openl10n\Bundle\ApiBundle\Controller\ProjectController
    name_prefix: openl10n_api_

language:
    type: rest
    resource: Openl10n\Bundle\ApiBundle\Controller\LanguageController
    parent: project
    name_prefix: openl10n_api_

resource:
    type: rest
    resource: Openl10n\Bundle\ApiBundle\Controller\ResourceController
    parent: project
    name_prefix: openl10n_api_

translation:
    type: rest
    resource: Openl10n\Bundle\ApiBundle\Controller\TranslationController
    parent: project
    name_prefix: openl10n_api_

translation_commit:
    type: rest
    resource: Openl10n\Bundle\ApiBundle\Controller\TranslationCommitController
    parent: project
    prefix: /projects/{project} # because parent doen't work here for manual definition
    name_prefix: openl10n_api_

# domain:
#     type: rest
#     resource: Openl10n\Bundle\ApiBundle\Controller\DomainController
#     parent: project
#     name_prefix: openl10n_api_

# openl10n_api_export:
#     path: /projects/{project}/domains/{domain}/translations.{locale}.{_format}
#     defaults: { _controller: Openl10nApiBundle:Export:export }
