# REST end-points
openl10n_api_rest:
    type: rest
    resource: "@Openl10nApiBundle/Resources/config/routing/rest.yml"

# Other routers
openl10n_api_misc:
    resource: "@Openl10nApiBundle/Resources/config/routing/misc.yml"
