project:
    type: rest
    resource: Openl10n\Bundle\ApiBundle\Controller\ProjectController
    name_prefix: openl10n_api_

domain:
    type: rest
    resource: Openl10n\Bundle\ApiBundle\Controller\DomainController
    parent: project
    name_prefix: openl10n_api_
